# Generated by Django 5.2.14 on 2026-05-20 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_customer_gender_salesperson_gender'),
    ]

    operations = [
    ]
